### ISSUE TITLE
Spaces appear as `%2520` (encode/decode issue)

### ISSUE THREAD

**Issue by saikadaramakaisosjupita** [zwbetz-gh/client-side-search-for-hugo#17]
Tested even with your own site. Shouldn't spaces be `%20`? It seems the `%` is being encoded also.

**Comment by zwbetz-gh** [comment]
Good catch. Fixed in https://github.com/zwbetz-gh/hugo-client-side-search-template/commit/b0e322c7e8bee8f00867e3924da5db3516194330
