### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by tyytytytyiigo** [zwbetz-gh/client-side-search-for-hugo#2]
Hi there. Do you have an idea how the JS file could be modified to support several `index.json` files based on site language? For example, `index.json` and `/fr/index.json`. So that, when the language is switched, the relevant index file content is pulled?

**Comment by zwbetz-gh** [comment]
Hi there. Unfortunately I don't know how to do this.

**Comment by dryscord** [comment]
See solution in issue #13
