### ISSUE TITLE
Feature Request: Change the style of a highlighted match

### ISSUE THREAD

**Issue by lrh11099** [zwbetz-gh/client-side-search-for-hugo#21]
I think `#ff0` works better as a base highlight colour. You can test it out. It works well in both light and dark modes (and if the text color is `#000`)

**Comment by zwbetz-gh** [comment]
Thanks, but I have no plans to change the highlighted matched color in the template.

Feel free to change it to whatever you like in your project 👍 

https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/7bd03a5eea6a9b26c221fd53a81e9c97ea66e115/assets/js/main.ts#L15

**Comment by lrh11099** [comment]
> Feel free to change it to whatever you like in your project 👍

I did. The beauty of open source. Added new features too.

**Comment by zwbetz-gh** [comment]
Glad to hear it.
